spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/mariadb
    username: username
    password: userpassword
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
server:
  port: 8088